package warre.me.backend.chared.domain.cards;

public enum CardType {
    ADVANCE_TO_GO_COLLECT_200,
    ADVANCE_TO_ILLINOIS_AVENUE,
    ADVANCE_TO_ST_CHARLES_PLACE,
    ADVANCE_TO_NEAREST_UTILITY,
    ADVANCE_TO_NEAREST_RAILROAD,
    BANK_PAYS_DIVIDEND_50,
    GET_OUT_OF_JAIL_FREE,
    GO_BACK_THREE_SPACES,
    GO_TO_JAIL,
    GENERAL_REPAIRS_PAY_PER_HOUSE_25_PER_HOTEL_100,
    TRIP_TO_READING_RAILROAD,
    ADVANCE_TO_BOARDWALK,
    ELECTED_CHAIRMAN_PAY_EACH_PLAYER_50,
    BUILDING_AND_LOAN_MATURES_COLLECT_150
}
